services:
  pokemon-app:
    image: pokemon:latest
    build:
      context: .
    container_name: pokemon-container
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pokemons
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - 8080:8080

  db:
    container_name: db-container
    image: postgres:16
    environment:
      - POSTGRES_DB=pokemons
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
    ports:
      - 8000:5432





#services:
#  pokemon-service:
#    container_name: pokemon-container
#    image: pokemon:latest
##    environment:
##      - 'POSTGRES_DB=jdbc:postgresql://postgres-db:5432/dbtest'
##      - 'POSTGRES_PASSWORD=123'
##      - 'POSTGRES_USER=admin'
##    depends_on:
##      - postgres-db
#    ports:
#      - '8080:8080'
#
#  postgres-db:
#    container_name: db-container
#    image: 'postgres:16'
#    environment:
#      - 'POSTGRES_DB=dbtest'
#      - 'POSTGRES_PASSWORD=123'
#      - 'POSTGRES_USER=admin'
#    ports:
#      - '8000:5432'