#spring:
#  datasource:
#    url: ${POSTGRES_DB}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: 'update'

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/pokemons
#    username: dev
#    password: cow
#  jpa:
#    hibernate:
#      ddl-auto: 'update'
